"""Add User to Message as Obj

Revision ID: 040f0f684dd4
Revises: 8d920d4bf525
Create Date: 2025-06-15 16:03:46.246932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '040f0f684dd4'
down_revision: Union[str, None] = '8d920d4bf525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'message', ['to_user_id'])
    op.drop_constraint(op.f('message_to_user_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_to_user_id_fkey'), 'message', 'users', ['to_user_id'], ['id'])
    op.drop_constraint(None, 'message', type_='unique')
    op.alter_column('message', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
