"""remove unqiue constraint for user messages

Revision ID: 1ab11c779174
Revises: 3e4afeb5aa77
Create Date: 2025-06-15 18:30:14.224138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ab11c779174'
down_revision: Union[str, None] = '3e4afeb5aa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_to_user_id_key'), 'message', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('message_to_user_id_key'), 'message', ['to_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
