"""Make from_user_id on message nullable

Revision ID: 315bfcb97e66
Revises: 1141ca794315
Create Date: 2025-06-18 07:50:03.691852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '315bfcb97e66'
down_revision: Union[str, None] = '1141ca794315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
