"""make cascading delete on user session

Revision ID: 8d920d4bf525
Revises: 8721d9e816e3
Create Date: 2025-06-13 05:18:41.153594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d920d4bf525'
down_revision: Union[str, None] = '8721d9e816e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('user_session_user_id_fkey'), 'user_session', type_='foreignkey')
    op.create_foreign_key(None, 'user_session', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.create_foreign_key(op.f('user_session_user_id_fkey'), 'user_session', 'users', ['user_id'], ['id'])
    op.alter_column('user_session', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
